\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{manconsulting}[2020/06/08 man pages documents class for consulting]
\LoadClass[a4paper]{book}
\RequirePackage[top=15mm,bottom=20mm,left=10mm,right=10mm]{geometry}
\RequirePackage{titlesec}
%\titlespacing{\subsection}{0pt}{0pt}{0pt}
\titlespacing{\subsubsection}{0pt}{0pt}{0pt}
\RequirePackage[scaled]{beramono}
\renewcommand*\familydefault{\ttdefault} %% Only if the base font of the document is to be typewriter style
\RequirePackage[T1]{fontenc}
\setcounter{tocdepth}{1}
